const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('oyaBrowser', {
  navigate: (url) => ipcRenderer.invoke('navigate', url),
  goBack: () => ipcRenderer.invoke('go-back'),
  goForward: () => ipcRenderer.invoke('go-forward'),
  reload: () => ipcRenderer.invoke('reload'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  getStatus: () => ipcRenderer.invoke('get-status'),
  enterBrowsing: () => ipcRenderer.invoke('enter-browsing'),
  showOverlay: () => ipcRenderer.invoke('show-overlay'),
  hideOverlay: () => ipcRenderer.invoke('hide-overlay'),
  toggleDevPanel: () => ipcRenderer.invoke('toggle-dev-panel'),
  // Tabs
  newTab: (url) => ipcRenderer.invoke('new-tab', url),
  closeTab: (id) => ipcRenderer.invoke('close-tab', id),
  activateTab: (id) => ipcRenderer.invoke('activate-tab', id),
  // Recording
  startRecording: () => ipcRenderer.invoke('start-recording'),
  stopRecording: () => ipcRenderer.invoke('stop-recording'),
  clearRecording: () => ipcRenderer.invoke('clear-recording'),
  saveRecording: (name, description) => ipcRenderer.invoke('save-recording', name, description),
  onRecordedSteps: (cb) => ipcRenderer.on('recorded-steps', (e, state) => cb(state)),
  // Events
  onUrlChanged: (cb) => ipcRenderer.on('url-changed', (e, url) => cb(url)),
  onTitleChanged: (cb) => ipcRenderer.on('title-changed', (e, title) => cb(title)),
  onWsStatus: (cb) => ipcRenderer.on('ws-status', (e, status) => cb(status)),
  onModeChanged: (cb) => ipcRenderer.on('mode-changed', (e, mode) => cb(mode)),
  onDevLog: (cb) => ipcRenderer.on('dev-log', (e, entry) => cb(entry)),
  onDevPanelState: (cb) => ipcRenderer.on('dev-panel-state', (e, open) => cb(open)),
  onInspectResult: (cb) => ipcRenderer.on('inspect-result', (e, result) => cb(result)),
  onViewSource: (cb) => ipcRenderer.on('view-source', (e, data) => cb(data)),
  onTabsUpdated: (cb) => ipcRenderer.on('tabs-updated', (e, tabs) => cb(tabs)),
  // Dev panel
  resizeDevPanel: (width) => ipcRenderer.invoke('resize-dev-panel', width),
  getPageSource: () => ipcRenderer.invoke('get-page-source'),
  devAction: (action, params) => ipcRenderer.invoke('dev-action', action, params),
  sendChat: (messages) => ipcRenderer.invoke('send-chat', messages),
  getFingerprint: () => ipcRenderer.invoke('get-fingerprint'),
  saveProfile: () => ipcRenderer.invoke('save-profile'),
  onProfileSaved: (cb) => ipcRenderer.on('profile-saved', (e, state) => cb(state)),
  onFingerprintChanged: (cb) => ipcRenderer.on('fingerprint-changed', (e, fp) => cb(fp)),
  // Updates
  getVersion: () => ipcRenderer.invoke('get-version'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (e, status) => cb(status)),
});
