/**
 * Code generation: a draft becomes a standalone Playwright module. Its text is
 * what people export, what the server stores, and what validation runs, so
 * the output must stay byte-for-byte stable.
 */
const { STEP } = require('../constants.cjs');
const { locatorCode } = require('./locators.cjs');
const { RESERVED, visibleOnly } = require('./rules.cjs');
const { normalizeDraft } = require('./normalize.cjs');
const { issues, variableNames } = require('./issues.cjs');

/** The module's fixed opening: its signature and where `expect` comes from. */
const HEADER = [
  '// Generated by Oya. Optional hooks power debugging; no Oya runtime is required.',
  'export default async function run(page, vars = {}, hooks = {}) {',
  "  const expect = hooks.expect || (await import('@playwright/test')).expect;",
];

/** The fixed helpers after the variables: the placeholder filler and the tab map. */
const HELPERS = [
  "  const value = x => String(x ?? '').replace(/\\{\\{([A-Za-z_]\\w*)\\}\\}/g, (_, key) => String(vars[key] ?? '')); ",
  "  const pages = hooks.pages || new Map([['main', page]]); let p = page;",
  // The role-name rule of workflow/locators.cjs roleName: exact, give or take icons around it.
  "  const named = x => new RegExp('^\\\\W*' + String(x).replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&') + '\\\\W*$');",
  // A step's recorded targets in order: the first that finds exactly one element, else the first.
  '  const first = async (...found) => { for (const l of found) if (await l.count() === 1) return l; return found[0]; };',
];

/** The module's opening: header, variable defaults and the missing-variable check, helpers. */
function preamble(draft, defaults) {
  const names = JSON.stringify(variableNames(draft));
  return [
    ...HEADER,
    `  vars = {...${JSON.stringify(defaults)}, ...vars};`,
    `  for (const key of ${names}) if (!Object.prototype.hasOwnProperty.call(vars, key) || vars[key] === undefined) throw new Error('Missing variable: ' + key);`,
    ...HELPERS,
  ];
}

/** Code for each action, given the step's locator, timeout option and value expressions. */
const ACTION_CODE = {
  navigate: (s) => `await p.goto(${s.val('url')}, ${s.timeout});`,
  go_back: (s) => `await p.goBack(${s.timeout});`,
  go_forward: (s) => `await p.goForward(${s.timeout});`,
  click: (s) => `await ${s.locator}.click(${s.timeout});`,
  double_click: (s) => `await ${s.locator}.dblclick(${s.timeout});`,
  hover: (s) => `await ${s.locator}.hover(${s.timeout});`,
  // A typeahead opens its suggestions on keystrokes, which a fill does not send: a combobox is typed into key by key.
  type: (s) =>
    comboboxOf(s.step)
      ? `await ${s.locator}.fill('', ${s.timeout}); await ${s.locator}.pressSequentially(${s.val('text')}, {delay: ${STEP.TYPE_DELAY_MS}, ...${s.timeout}});`
      : `await ${s.locator}.fill(${s.val('text')}, ${s.timeout});`,
  select_option: (s) => `await ${s.locator}.selectOption({label:${s.val('option')}}, ${s.timeout});`,
  upload_file: (s) => `await ${s.locator}.setInputFiles(${s.val('file')}, ${s.timeout});`,
  press_key: (s) => `await p.keyboard.press(${s.val('key')});`,
  scroll: (s) =>
    `await p.mouse.wheel(0, ${(s.step.direction === 'up' ? -1 : 1) * (Number(s.step.amount) || STEP.DEFAULT_SCROLL)});`,
  wait: (s) => `await ${s.locator}.waitFor({state:'visible', timeout:${s.step.timeout}});`,
  assert_visible: (s) => `await expect(${s.locator}).toBeVisible(${s.timeout});`,
  assert_text: (s) => `await expect(${s.locator}).toHaveText(${s.val('expected')}, ${s.timeout});`,
  assert_value: (s) => `await expect(${s.locator}).toHaveValue(${s.val('expected')}, ${s.timeout});`,
  assert_url: (s) => `await expect(p).toHaveURL(${s.val('expected')}, ${s.timeout});`,
  // The page the recording reached, by its address without the query: a session
  // token or a tracking tag there changes every visit, as does Amazon's `/ref=`
  // path segment. A route in the fragment (`#/active`) is part of the page, any
  // other fragment is not. The query parameters a filter or sort set are named.
  assert_page: (s) =>
    `{ const e = new URL(${s.val('expected')}); const path = x => x.pathname.replace(/\\/ref=[^/]*/g, ''); await expect(p).toHaveURL(u => u.origin === e.origin && path(u) === path(e) && (!e.hash.startsWith('#/') || u.hash === e.hash)${paramsCheck(s.step)}, ${s.timeout}); }`,
  checkpoint: () =>
    "if (!hooks.checkpoint) throw new Error('This workflow requires a human checkpoint'); await hooks.checkpoint(p);",
};

/**
 * The step's locator code: its first target, or, when it has others, the first
 * of its first few targets that finds exactly one element. A module run on its
 * own then survives a page that renamed one handle, as a validation run does
 * by repairing the step.
 */
function locatorFor(step, owner) {
  const code = (c) => locatorCode(c, owner, `value(${JSON.stringify(c.value)})`) + visibleOnly(step.action);
  const found = step.candidates.slice(0, STEP.MAX_FALLBACKS).map(code);
  if (found.length <= 1) return found[0] ?? null;
  return `(await first(${found.join(', ')}))`;
}

/** Whether a step types into a combobox: a search box with suggestions. */
const comboboxOf = (step) => step.el?.role === 'combobox' || step.candidates.some((c) => c.role === 'combobox');

/** The check that a page's named query parameters (a filter, a sort) are as recorded, or nothing. */
function paramsCheck(step) {
  const names = String(step.params || '')
    .split(',')
    .filter(Boolean);
  return names.length ? ` && ${JSON.stringify(names)}.every(k => u.searchParams.get(k) === e.searchParams.get(k))` : '';
}

/** What an action's code is built from: the locator through the step's frames, and value expressions. */
function actionContext(step) {
  let owner = 'p';
  for (const frame of step.frames) owner += `.frameLocator(${JSON.stringify(frame)})`;
  const locator = locatorFor(step, owner);
  const val = (key) => `value(${JSON.stringify(step[key] ?? '')})`;
  return { step, locator, val, timeout: `{timeout:${step.timeout}}` };
}

/** The line of code that performs the step (unknown actions never get here: issues() stops them). */
function actionCode(step) {
  const ctx = actionContext(step);
  return Object.hasOwn(ACTION_CODE, step.action) ? ACTION_CODE[step.action](ctx) : undefined;
}

/** Opens a step's block: the shouldRun guard, its tab, and the beforeStep hook. */
function openStep(lines, step, id) {
  const tab = JSON.stringify(step.tab);
  lines.push(`  if (!hooks.shouldRun || hooks.shouldRun(${id})) {`, `  // ${step.action}`);
  lines.push(
    `  if (!pages.has(${tab})) pages.set(${tab}, await page.context().newPage());`,
    `  p = pages.get(${tab});`,
  );
  lines.push('  try {', `    await hooks.beforeStep?.(${id}, p);`);
}

/** Appends one step's guarded block; `mapping` records the line its action is on. */
function addStep(lines, mapping, step) {
  const id = JSON.stringify(step.id);
  mapping[step.id] = lines.length + 1;
  openStep(lines, step, id);
  const command = actionCode(step);
  mapping[step.id] = lines.length + 1;
  lines.push('    ' + command, `    await hooks.afterStep?.(${id}, p);`);
  lines.push(`  } catch (error) { await hooks.failedStep?.(${id}, error, p); throw error; }`, '  }');
}

/** Refuses a draft with problems or a variable name that would reach a prototype. */
function checkGeneratable(draft, problems) {
  if (problems.length) throw new Error(problems.map((issue) => issue.message).join('\n'));
  if (variableNames(draft).some((name) => RESERVED.includes(name))) throw new Error('Reserved variable name');
}

/** Default values for the variables that have one and are not secret. */
function variableDefaults(draft) {
  const withDefault = Object.entries(draft.variables).filter(([, v]) => !v.secret && v.default !== undefined);
  return Object.fromEntries(withDefault.map(([key, v]) => [key, v.default]));
}

/** The Playwright module for a draft: `{ code, mapping (step id → line), issues }`. Throws if it cannot run. */
function generate(input) {
  const draft = normalizeDraft(input);
  const problems = issues(draft);
  checkGeneratable(draft, problems);
  const lines = preamble(draft, variableDefaults(draft));
  const mapping = {};
  for (const step of draft.steps.filter((s) => s.enabled)) addStep(lines, mapping, step);
  lines.push('}');
  return { code: lines.join('\n') + '\n', mapping, issues: problems };
}

module.exports = { generate };
