/**
 * Code generation: a draft becomes a standalone Playwright module. Its text is
 * what people export, what the server stores, and what validation runs, so
 * the output must stay byte-for-byte stable.
 */
const { STEP } = require('../constants.cjs');
const { locatorCode } = require('./locators.cjs');
const { RESERVED } = require('./rules.cjs');
const { normalizeDraft } = require('./normalize.cjs');
const { issues, variableNames } = require('./issues.cjs');

/** The module's fixed opening: its signature and where `expect` comes from. */
const HEADER = [
  '// Generated by Oya. Optional hooks power debugging; no Oya runtime is required.',
  'export default async function run(page, vars = {}, hooks = {}) {',
  "  const expect = hooks.expect || (await import('@playwright/test')).expect;",
];

/** The fixed helpers after the variables: the placeholder filler and the tab map. */
const HELPERS = [
  "  const value = x => String(x ?? '').replace(/\\{\\{([A-Za-z_]\\w*)\\}\\}/g, (_, key) => String(vars[key] ?? '')); ",
  "  const pages = hooks.pages || new Map([['main', page]]); let p = page;",
];

/** The module's opening: header, variable defaults and the missing-variable check, helpers. */
function preamble(draft, defaults) {
  const names = JSON.stringify(variableNames(draft));
  return [
    ...HEADER,
    `  vars = {...${JSON.stringify(defaults)}, ...vars};`,
    `  for (const key of ${names}) if (!Object.prototype.hasOwnProperty.call(vars, key) || vars[key] === undefined) throw new Error('Missing variable: ' + key);`,
    ...HELPERS,
  ];
}

/** Code for each action, given the step's locator, timeout option and value expressions. */
const ACTION_CODE = {
  navigate: (s) => `await p.goto(${s.val('url')}, ${s.timeout});`,
  click: (s) => `await ${s.locator}.click(${s.timeout});`,
  type: (s) => `await ${s.locator}.fill(${s.val('text')}, ${s.timeout});`,
  select_option: (s) => `await ${s.locator}.selectOption({label:${s.val('option')}}, ${s.timeout});`,
  upload_file: (s) => `await ${s.locator}.setInputFiles(${s.val('file')}, ${s.timeout});`,
  press_key: (s) => `await p.keyboard.press(${s.val('key')});`,
  scroll: (s) =>
    `await p.mouse.wheel(0, ${(s.step.direction === 'up' ? -1 : 1) * (Number(s.step.amount) || STEP.DEFAULT_SCROLL)});`,
  wait: (s) => `await ${s.locator}.waitFor({state:'visible', timeout:${s.step.timeout}});`,
  assert_visible: (s) => `await expect(${s.locator}).toBeVisible(${s.timeout});`,
  assert_text: (s) => `await expect(${s.locator}).toHaveText(${s.val('expected')}, ${s.timeout});`,
  assert_value: (s) => `await expect(${s.locator}).toHaveValue(${s.val('expected')}, ${s.timeout});`,
  assert_url: (s) => `await expect(p).toHaveURL(${s.val('expected')}, ${s.timeout});`,
  checkpoint: () =>
    "if (!hooks.checkpoint) throw new Error('This workflow requires a human checkpoint'); await hooks.checkpoint(p);",
};

/** What an action's code is built from: the locator through the step's frames, and value expressions. */
function actionContext(step) {
  let owner = 'p';
  for (const frame of step.frames) owner += `.frameLocator(${JSON.stringify(frame)})`;
  const first = step.candidates[0];
  const locator = first ? locatorCode(first, owner, `value(${JSON.stringify(first.value)})`) : null;
  const val = (key) => `value(${JSON.stringify(step[key] ?? '')})`;
  return { step, locator, val, timeout: `{timeout:${step.timeout}}` };
}

/** The line of code that performs the step (unknown actions never get here: issues() stops them). */
function actionCode(step) {
  const ctx = actionContext(step);
  return Object.hasOwn(ACTION_CODE, step.action) ? ACTION_CODE[step.action](ctx) : undefined;
}

/** Opens a step's block: the shouldRun guard, its tab, and the beforeStep hook. */
function openStep(lines, step, id) {
  const tab = JSON.stringify(step.tab);
  lines.push(`  if (!hooks.shouldRun || hooks.shouldRun(${id})) {`, `  // ${step.action}`);
  lines.push(
    `  if (!pages.has(${tab})) pages.set(${tab}, await page.context().newPage());`,
    `  p = pages.get(${tab});`,
  );
  lines.push('  try {', `    await hooks.beforeStep?.(${id}, p);`);
}

/** Appends one step's guarded block; `mapping` records the line its action is on. */
function addStep(lines, mapping, step) {
  const id = JSON.stringify(step.id);
  mapping[step.id] = lines.length + 1;
  openStep(lines, step, id);
  const command = actionCode(step);
  mapping[step.id] = lines.length + 1;
  lines.push('    ' + command, `    await hooks.afterStep?.(${id}, p);`);
  lines.push(`  } catch (error) { await hooks.failedStep?.(${id}, error, p); throw error; }`, '  }');
}

/** Refuses a draft with problems or a variable name that would reach a prototype. */
function checkGeneratable(draft, problems) {
  if (problems.length) throw new Error(problems.map((issue) => issue.message).join('\n'));
  if (variableNames(draft).some((name) => RESERVED.includes(name))) throw new Error('Reserved variable name');
}

/** Default values for the variables that have one and are not secret. */
function variableDefaults(draft) {
  const withDefault = Object.entries(draft.variables).filter(([, v]) => !v.secret && v.default !== undefined);
  return Object.fromEntries(withDefault.map(([key, v]) => [key, v.default]));
}

/** The Playwright module for a draft: `{ code, mapping (step id → line), issues }`. Throws if it cannot run. */
function generate(input) {
  const draft = normalizeDraft(input);
  const problems = issues(draft);
  checkGeneratable(draft, problems);
  const lines = preamble(draft, variableDefaults(draft));
  const mapping = {};
  for (const step of draft.steps.filter((s) => s.enabled)) addStep(lines, mapping, step);
  lines.push('}');
  return { code: lines.join('\n') + '\n', mapping, issues: problems };
}

module.exports = { generate };
