/**
 * Every number playbooks, runs and recordings run on, by name: limits on what a
 * recording may hold, replay timings and how long runs and recordings are kept.
 */

/** The `schemaVersion` of a workflow draft (steps generated by the browser's workflow engine). */
export const WORKFLOW_SCHEMA = 2;
/** Steps a recording or a flow buffer may hold. */
export const MAX_STEPS = 500;
/** Longest string kept from a recorded step or saved prompt. */
export const MAX_LEN = 2000;
/** Largest scroll a recorded step may carry, in pixels. */
export const MAX_SCROLL_AMOUNT = 100_000;
/** Pixels a scroll step moves when it recorded no amount. */
export const DEFAULT_SCROLL_PX = 500;
/** Longest variable name derived from an element's handle. */
export const MAX_VARIABLE_NAME = 40;
/** The first suffix a second field with the same derived name gets (`name2`). */
export const FIRST_NAME_SUFFIX = 2;
/** Shorter values are not substituted into the prompt: they would match inside other words. */
export const MIN_PROMPT_VALUE_LEN = 3;
/** How many steps after typing a value a click on a label holding it still counts as picking it. */
export const ECHO_WINDOW = 3;
/** The shortest clicked label that counts as a value the person named in their prompt. */
export const MIN_PICK_LEN = 6;
/** The shortest radio or checkbox label that counts as a named choice ("No"). */
export const MIN_CHOICE_LEN = 2;
/** Typed text of at least this many words, not taken from the prompt, is an answer the model writes fresh each run. */
export const MIN_ANSWER_WORDS = 4;
/** Longest answer the model may put in one field. */
export const MAX_ANSWER_CHARS = 2000;

/** Times replay re-analyzes the page looking for a recorded element. */
export const FIND_ATTEMPTS = 5;
/** Pause between those analyses. */
export const FIND_RETRY_MS = 1000;

/**
 * How long a replay waits before each step, and after one that changed the page.
 *
 * A replay knows every step in advance, so left alone it fires them as fast as
 * the network allows, and that is what gives it away. Amazon let the agent
 * through twice at fourteen seconds a step and challenged the replay at eight.
 * A person reads the page they just loaded before acting on it, so a replay does
 * too: a short jittered pause before each action, a longer one once the page has
 * changed under it. This is deliberately not tunable down to zero, a replay
 * that beats a human to the click is a replay that gets caught.
 */
export const REPLAY_PAUSE_MS = { min: 350, max: 1200 };

/** The same, after a navigation or a click that moved the page: time to read it. */
export const REPLAY_SETTLE_MS = { min: 900, max: 2600 };
/** Navigation waits on slow sites. */
export const NAVIGATE_TIMEOUT_MS = 90_000;
/** A whole workflow run in the browser (10 minutes). */
export const WORKFLOW_TIMEOUT_MS = 600_000;

/** How long a run waits for a person before failing (30 minutes). */
export const HUMAN_WAIT_MS = 1_800_000;
/** How long a finished run stays pollable (an hour). */
export const RUN_KEEP_MS = 3_600_000;

/** How often a recording browser is polled for new steps. */
export const RECORD_POLL_MS = 5000;
/** A recording stops on its own after this long, and a stopped one is kept this long (30 minutes). */
export const RECORD_MAX_MS = 1_800_000;
/** Milliseconds in a minute. */
export const MS_PER_MINUTE = 60_000;
